### ISSUE TITLE
TypeError: Cannot read property 'emoji' of undefined

### ISSUE THREAD

**Issue by wonderlandpark** [sannoob/spagination#5]
```
TypeError: Cannot read property 'emoji' of undefined
    at /home/wonderlandpark/wonderbot/node_modules/pagination-is-noob/src/lib/Pagination.js:87:67
    at Array.findIndex (<anonymous>)
    at PaginationManager._handleControlKeys (/home/wonderlandpark/wonderbot/node_modules/pagination-is-noob/src/lib/Pagination.js:87:30)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async PaginationManager.send (/home/wonderlandpark/wonderbot/node_modules/pagination-is-noob/src/lib/Pagination.js:62:5)
```

**Comment by wonderlandpark** [comment]
Alive.
